name: React Website Build Upload

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['16'] 

      steps:
        uses: actions/checkout@v1
        run: npm install
        run: npm run build
        run: npm test
